insert into words (english, turkish, cefr_level, part_of_speech, example_sentence) values
('hello', 'merhaba', 'A1', 'phrase', 'Hello, how are you?'),
('goodbye', 'güle güle', 'A1', 'phrase', 'Goodbye, see you tomorrow.'),
('thank you', 'teşekkür ederim', 'A1', 'phrase', 'Thank you for your help.'),
('please', 'lütfen', 'A1', 'adverb', 'Please sit down.'),
('yes', 'evet', 'A1', 'adverb', 'Yes, I understand.'),
('no', 'hayır', 'A1', 'adverb', 'No, I do not agree.'),
('water', 'su', 'A1', 'noun', 'Can I have some water?'),
('food', 'yemek', 'A1', 'noun', 'The food is delicious.'),
('house', 'ev', 'A1', 'noun', 'This is my house.'),
('family', 'aile', 'A1', 'noun', 'I love my family.'),
('friend', 'arkadaş', 'A1', 'noun', 'She is my best friend.'),
('school', 'okul', 'A1', 'noun', 'I go to school every day.'),
('book', 'kitap', 'A1', 'noun', 'I am reading a book.'),
('day', 'gün', 'A1', 'noun', 'Today is a good day.'),
('time', 'zaman', 'A1', 'noun', 'What time is it?'),
('work', 'çalışmak', 'A1', 'verb', 'I work at a hospital.'),
('eat', 'yemek yemek', 'A1', 'verb', 'I eat breakfast every morning.'),
('drink', 'içmek', 'A1', 'verb', 'I drink coffee in the morning.'),
('go', 'gitmek', 'A1', 'verb', 'I go to work by bus.'),
('come', 'gelmek', 'A1', 'verb', 'Please come here.'),
('see', 'görmek', 'A1', 'verb', 'I can see the mountains.'),
('know', 'bilmek', 'A1', 'verb', 'Do you know the answer?'),
('want', 'istemek', 'A1', 'verb', 'I want to learn English.'),
('like', 'beğenmek', 'A1', 'verb', 'I like chocolate.'),
('have', 'sahip olmak', 'A1', 'verb', 'I have two cats.'),
('big', 'büyük', 'A1', 'adjective', 'This is a big house.'),
('small', 'küçük', 'A1', 'adjective', 'She has a small dog.'),
('good', 'iyi', 'A1', 'adjective', 'You are doing a good job.'),
('new', 'yeni', 'A1', 'adjective', 'I have a new phone.'),
('old', 'eski', 'A1', 'adjective', 'This is an old building.'),
('happy', 'mutlu', 'A1', 'adjective', 'I am very happy today.'),
('tired', 'yorgun', 'A1', 'adjective', 'I am tired after work.'),
('name', 'isim', 'A1', 'noun', 'My name is Alex.'),
('city', 'şehir', 'A1', 'noun', 'Istanbul is a beautiful city.'),
('country', 'ülke', 'A1', 'noun', 'Turkey is a beautiful country.'),
('money', 'para', 'A1', 'noun', 'I need some money.'),
('car', 'araba', 'A1', 'noun', 'I drive my car to work.'),
('phone', 'telefon', 'A1', 'noun', 'My phone is in my bag.'),
('computer', 'bilgisayar', 'A1', 'noun', 'I use a computer at work.'),
('door', 'kapı', 'A1', 'noun', 'Please close the door.'),
('street', 'sokak', 'A1', 'noun', 'The shop is on this street.'),
('morning', 'sabah', 'A1', 'noun', 'Good morning!'),
('night', 'gece', 'A1', 'noun', 'Good night!'),
('week', 'hafta', 'A1', 'noun', 'I work five days a week.'),
('year', 'yıl', 'A1', 'noun', 'I study English every year.'),
('help', 'yardım etmek', 'A1', 'verb', 'Can you help me?'),
('speak', 'konuşmak', 'A1', 'verb', 'Do you speak English?'),
('read', 'okumak', 'A1', 'verb', 'I read a book every night.'),
('write', 'yazmak', 'A1', 'verb', 'Please write your name here.'),
('open', 'açmak', 'A1', 'verb', 'Please open the window.'),
('close', 'kapatmak', 'A1', 'verb', 'Please close the door.'),
('fast', 'hızlı', 'A1', 'adjective', 'He runs very fast.'),
('slow', 'yavaş', 'A1', 'adjective', 'The bus is very slow today.'),
('hot', 'sıcak', 'A1', 'adjective', 'The tea is very hot.'),
('cold', 'soğuk', 'A1', 'adjective', 'It is cold outside.'),
('beautiful', 'güzel', 'A1', 'adjective', 'The view is beautiful.'),
('easy', 'kolay', 'A1', 'adjective', 'This exercise is easy.'),
('difficult', 'zor', 'A1', 'adjective', 'This question is difficult.'),
('wait', 'beklemek', 'A1', 'verb', 'Please wait a moment.'),
('start', 'başlamak', 'A1', 'verb', 'Let us start the lesson.'),
('finish', 'bitirmek', 'A1', 'verb', 'I will finish this today.');
